SELECT  NAME,  SCHEMA, TBNAME,
CASE TRIGEVENT
    WHEN 'I' THEN 'Insert'
    WHEN 'U' THEN 'Update'
    WHEN 'D' THEN 'Delete'
    END as EVENT,
CAST(STATEMENT as varchar(8000)) as TEXT
FROM SYSIBM.SYSTRIGGERS
WHERE SCHEMA LIKE 'INM%'
ORDER BY SCHEMA, TBNAME
;

