SET NOCOUNT ON

DECLARE @SQL AS NVARCHAR(4000)
SELECT @SQL = (
SELECT 'TRUNCATE TABLE tmp.' + TABLE_NAME + ';'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE table_type = 'BASE TABLE'
		AND [TABLE_SCHEMA] = 'tmp'
		FOR XML PATH(''))

EXEC sp_executesql @SQL